# -*- coding: utf-8 -*-
"""day14_crypto_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mpak_ME-3-yWX01CayY-iXbLua9vTCjM
"""

!pip install requests pandas
import requests
import pandas as pd
url = "https://api.coingecko.com/api/v3/coins/markets"
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 10,
    "page": 1,
    "sparkline": False
}

response = requests.get(url, params=params)
data = response.json()
df = pd.DataFrame(data, columns=["name", "symbol", "current_price", "market_cap", "price_change_percentage_24h"])

print("📊 Top 10 Cryptocurrencies:")
print(df)

# Sort by price change
print("\n📈 Sorted by 24h price change:")
print(df.sort_values(by="price_change_percentage_24h", ascending=False))
# Show coins with more than 0% gain in 24h
gainers = df[df["price_change_percentage_24h"] > 0]
print("\n🚀 Coins up more than 0% in last 24h:")
print(gainers)