# -*- coding: utf-8 -*-
"""day12_expense_visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PV39H9EYFGmqewJsWz8J4wtDpwfhwxOr
"""

!!pip install matplotlib
import pandas as pd
import matplotlib.pyplot as plt

FILENAME = "expenses.txt"

def add_expense(amount, category):
    with open(FILENAME, "a") as file:
        file.write(f"{amount},{category}\n")
    print("✅ Expense added!")

def view_expenses():
    try:
        with open(FILENAME, "r") as file:
            expenses = file.readlines()
            if not expenses:
                print("📭 No expenses recorded yet.")
                return
            total = 0
            print("\n--- Your Expenses ---")
            for line in expenses:
                amount, category = line.strip().split(",")
                total += float(amount)
                print(f"💵 {amount} - {category}")
            print(f"\n💰 Total: {total}")
    except FileNotFoundError:
        print("📭 No expense file found. Add your first expense!")

while True:
    print("\n--- Expense Tracker ---")
    print("1. Add Expense")
    print("2. View Expenses")
    print("3. Exit")

    choice = input("Choose an option: ")

    if choice == "1":
        try:
            amount = float(input("Enter amount: "))
            category = input("Enter category: ")
            add_expense(amount, category)
        except ValueError:
            print("⚠️ Please enter a valid number!")
    elif choice == "2":
        view_expenses()
    elif choice == "3":
        print("👋 Goodbye!")
        break
    else:
        print("❌ Invalid choice, try again.")
def add_expense(amount, category):
    with open(FILENAME, "a") as file:
        file.write(f"{amount},{category}\n")


  # Load CSV into a DataFrame
df = pd.read_csv("expenses.txt", names=["Amount", "Category"], skiprows=0)

category_totals = df.groupby("Category")["Amount"].sum()

# Bar chart
plt.figure(figsize=(8,5))
category_totals.plot(kind="bar", color="skyblue")
plt.title("💰 Spending by Category")
plt.xlabel("Category")
plt.ylabel("Total Amount")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(6,6))
category_totals.plot(kind="pie", autopct='%1.1f%%', startangle=90)
plt.title("📊 Spending Distribution")
plt.ylabel("")  # Hide y-axis label
plt.show()