# -*- coding: utf-8 -*-
"""day13_weather_api.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_HTQR-Xy8RiMWHCDrE23kWVLwMX9NAC
"""

!pip install requests
import requests
API_KEY = "47135d7b6592f11babdc336266b49f9e"  # Replace with your key
BASE_URL = "http://api.openweathermap.org/data/2.5/weather"

city = input("🌍 Enter city name: ")
params = {
    "q": city,
    "appid": API_KEY,
    "units": "metric"  # Celsius
}

response = requests.get(BASE_URL, params=params)

if response.status_code == 200:
    data = response.json()
    weather = data["weather"][0]["description"]
    temp = data["main"]["temp"]
    feels_like = data["main"]["feels_like"]
    humidity = data["main"]["humidity"]

    print(f"📍 City: {city}")
    print(f"🌤 Weather: {weather}")
    print(f"🌡 Temp: {temp}°C (Feels like: {feels_like}°C)")
    print(f"💧 Humidity: {humidity}%")
else:
    print("⚠️ City not found or API error.")