# -*- coding: utf-8 -*-
"""day11_pandas_expense_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFwIzqdaCS-reShH2jZWty-LS5-dx_Hw
"""

!pip install pandas
import pandas as pd
FILENAME = "expenses.txt"

def add_expense(amount, category):
    with open(FILENAME, "a") as file:
        file.write(f"{amount},{category}\n")
    print("✅ Expense added!")

def view_expenses():
    try:
        with open(FILENAME, "r") as file:
            expenses = file.readlines()
            if not expenses:
                print("📭 No expenses recorded yet.")
                return
            total = 0
            print("\n--- Your Expenses ---")
            for line in expenses:
                amount, category = line.strip().split(",")
                total += float(amount)
                print(f"💵 {amount} - {category}")
            print(f"\n💰 Total: {total}")
    except FileNotFoundError:
        print("📭 No expense file found. Add your first expense!")

while True:
    print("\n--- Expense Tracker ---")
    print("1. Add Expense")
    print("2. View Expenses")
    print("3. Exit")

    choice = input("Choose an option: ")

    if choice == "1":
        try:
            amount = float(input("Enter amount: "))
            category = input("Enter category: ")
            add_expense(amount, category)
        except ValueError:
            print("⚠️ Please enter a valid number!")
    elif choice == "2":
        view_expenses()
    elif choice == "3":
        print("👋 Goodbye!")
        break
    else:
        print("❌ Invalid choice, try again.")
def add_expense(amount, category):
    with open(FILENAME, "a") as file:
        file.write(f"{amount},{category}\n")


  # Load CSV into a DataFrame
df = pd.read_csv("expenses.txt", names=["Amount", "Category"], skiprows=0)

# Show data
print("📄 Expense Data:")
print(df)

# Total spent
total = df["Amount"].sum()
print(f"\n💰 Total spent: {total}")

# Total per category
print("\n📊 Spending by category:")
print(df.groupby("Category")["Amount"].sum())

# Show expenses greater than 100
print("\n💵 Expenses > 100:")
print(df[df["Amount"] > 100])