# -*- coding: utf-8 -*-
"""day2_simple_calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128YSlYyDLJpxOeGJjkwGBBzCAdNdOwvR
"""

print("Simple Calculator")

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
operation = input("Choose operation (+, -, *, /): ")

if operation == "+":
    result = num1 + num2
elif operation == "-":
    result = num1 - num2
elif operation == "*":
    result = num1 * num2
elif operation == "/":
    result = num1 / num2
else:
    result = "Invalid operation"

print("Result:", result)