# -*- coding: utf-8 -*-
"""day2_variables_input.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3-6cDZcNfA7WiYa5RB2NmEr36PmOpxQ
"""

# Day 2 - Variables, Input, and Output

# Variables and data types
name = "Alice"        # string
age = 25              # integer
height = 5.6          # float
is_coder = True       # boolean

print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Is a coder?", is_coder)

# User input
your_name = input("What's your name? ")
your_age = input("How old are you? ")

# Type conversion
your_age = int(your_age)  # convert string to int

print(f"Nice to meet you, {your_name}! You'll be {your_age + 1} next year.")