# -*- coding: utf-8 -*-
"""day4_password_checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lLaVdWaLsEyL4TM-BnXFqm_4mlnPzKt
"""

correct_password = "OpenAI"
attempts = 3

while attempts > 0:
    guess = input("Enter the password: ")
    if guess == correct_password:
        print("✅ Access granted.")
        break
    else:
        print("❌ Wrong password.")
        attempts -= 1

if attempts == 0:
    print("🔒 Access denied. You're locked out.")