# -*- coding: utf-8 -*-
"""day4_loops_basics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQpOukWwQ-Fa4pK8-xdi6_yBDUHxDZJY
"""

# For loop: Print numbers 1 to 5
for i in range(1, 6):
    print("Number:", i)

# While loop: Countdown
count = 5
while count > 0:
    print("Countdown:", count)
    count -= 1

# Using break and continue
for i in range(1, 10):
    if i == 5:
        print("Hit 5, breaking!")
        break
    elif i == 3:
        print("Skipping 3")
        continue
    print("i is:", i)