# -*- coding: utf-8 -*-
"""day5_lists_dicts.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ac3--Sh7HjEf5QnL4MNaLzjUWF8XmzjP
"""



# Lists
fruits = ["apple", "banana", "mango"]

print("First fruit:", fruits[0])
print("All fruits:")
for fruit in fruits:
    print("-", fruit)

# Add an item
fruits.append("orange")
print("After adding:", fruits)

# Dictionary
person = {
    "name": "Alice",
    "age": 28,
    "is_student": True
}

print("Name:", person["name"])
print("Keys:")
for key in person:
    print(key, "→", person[key])