# -*- coding: utf-8 -*-
"""day5_contact_book.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOSitqWSPYuCuZhohV8RzbOu9uq66Tyy
"""

contacts = {}

while True:
    print("\n--- Contact Book ---")
    print("1. Add contact")
    print("2. View contacts")
    print("3. Exit")

    choice = input("Choose an option: ")

    if choice == "1":
        name = input("Enter name: ")
        phone = input("Enter phone: ")
        contacts[name] = phone
        print(f"Added {name}")
    elif choice == "2":
        print("\nSaved Contacts:")
        for name, phone in contacts.items():
            print(f"{name} → {phone}")
    elif choice == "3":
        print("Goodbye!")
        break
    else:
        print("Invalid choice.")