# -*- coding: utf-8 -*-
"""day6_functions_fibonacci.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1siUGpSjVqfrr1rjEskY78Q3ktj4hwoqw
"""

# Simple function
def greet(name):
    print(f"Hello, {name}!")

greet("Vinod")

# Function with return value
def square(n):
    return n * n

print("Square of 5 is:", square(5))
def generate_fibonacci(n):
    sequence = []
    a, b = 0, 1
    while len(sequence) < n:
        sequence.append(a)
        a, b = b, a + b
    return sequence

# Example usage
print("First 10 Fibonacci numbers:")
print(generate_fibonacci(10))
def generate_fibonacci(n):
    sequence = []
    a, b = 0, 1
    while len(sequence) < n:
        sequence.append(a)
        a, b = b, a + b
    return sequence

print("🔢 Fibonacci Generator")
count = int(input("How many numbers to generate? "))
fib = generate_fibonacci(count)
print("Here you go:")
print(fib)