# -*- coding: utf-8 -*-
"""day7_file_handling_notes_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8T-tk_GnzAONXglk882oF0G-BV7672z
"""

# Writing to a file
with open("my_file.txt", "w") as file:
    file.write("This is a saved note.\n")
    file.write("It will stay here even if you run it again.\n")

# Reading from a file
with open("my_file.txt", "r") as file:
    contents = file.read()
    print("File contents:")
    print(contents)

FILENAME = "notes.txt"

def save_note(note):
    with open(FILENAME, "a") as file:
        file.write(note + "\n")

def view_notes():
    try:
        with open(FILENAME, "r") as file:
            notes = file.readlines()
            print("\nYour Notes:")
            for line in notes:
                print("- " + line.strip())
    except FileNotFoundError:
        print("No notes yet!")

while True:
    print("\n--- Notes App ---")
    print("1. Add Note")
    print("2. View Notes")
    print("3. Exit")

    choice = input("Choose an option: ")

    if choice == "1":
        note = input("Enter your note: ")
        save_note(note)
        print("✅ Note saved!")
    elif choice == "2":
        view_notes()
    elif choice == "3":
        print("Goodbye!")
        break
    else:
        print("Invalid option.")