# -*- coding: utf-8 -*-
"""day8_chatbot_basic.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5b09UXDlAVp3KsNL34vItipF3WQJro7
"""

import datetime

chat_history = []

def respond_to_user(message):
    chat_history.append(message)
    message = message.lower()

    if "your name" in message:
        return "I'm PyBot — your first chatbot 🤖"
    elif "hello" in message or "hi" in message:
        return "Hello there! 👋"
    elif "how are you" in message:
        return "I'm just code, but I'm doing great. Thanks for asking!"
    elif "bye" in message:
      return "Goodbye! Come back soon 👋"
    elif "time" in message:
        now = datetime.datetime.now()
        return "⏰ It's " + now.strftime("%H:%M:%S")
    elif "history" in message:
        return "You said: " + ", ".join(chat_history)
    else:
        return "Hmm... I'm still learning."

print("🤖 Welcome to ChatBot 1.0")
while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        print("Chatbot: See you later!")
        break

    response = respond_to_user(user_input)
    print("Chatbot:", response)

