# -*- coding: utf-8 -*-
"""day9_error_handling_calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rya5svnhbpwQ5kr9ADzE0SoQUCDwLu1m
"""

def calculator():
    print("🧮 Welcome to CLI Calculator!")

    while True:
        try:
            num1 = float(input("Enter first number: "))
            operator = input("Enter operator (+, -, *, /): ")
            num2 = float(input("Enter second number: "))

            if operator == "+":
                result = num1 + num2
            elif operator == "-":
                result = num1 - num2
            elif operator == "*":
                result = num1 * num2
            elif operator == "/":
                if num2 == 0:
                    raise ZeroDivisionError
                result = num1 / num2
            else:
                print("❌ Invalid operator!")
                continue

            print("✅ Result:", result)

        except ValueError:
            print("⚠️ Please enter numbers only!")
        except ZeroDivisionError:
            print("⚠️ Cannot divide by zero!")

        choice = input("Do you want to calculate again? (y/n): ").lower()
        if choice != "y":
            print("Goodbye!")
            break

calculator()