# -*- coding: utf-8 -*-
"""hello_world_day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_kxUgdVn_BXFdfx3Dv7XVg_rLJre4_x
"""

print("Hello AI World This is Day1 of my AI journey")

